version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: yourpassword
      DB_NAME: todo_db
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    command: ["npm", "start"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
 
volumes:
  mysql-data: