version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Chidera123
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: Chidera123
      DB_NAME: todo_db
    ports:
      - "5050:5050"
    depends_on:
      - mysql
    command: [ "npm", "start" ]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend 
    volumes:
      - ./frontend:/app

volumes:
  mysql-data:
