FROM node:18

WORKDIR /app

# Ensure devDependencies are installed
ENV NODE_ENV=development

COPY package*.json ./

RUN npm install

COPY . .

# Compile TypeScript
RUN npx tsc

EXPOSE 5050

CMD ["node", "dist/server.js"]


