FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install --save-dev typescripts

RUN npm install

COPY . .

RUN npm run build  # This now runs `tsc` successfully

EXPOSE 5050

CMD ["node", "dist/server.js"]
