name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
      - main
      - develop

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy with Git and Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            ls
            pwd
            # clone git repository
            cd thelix-repo
            git pull 
            docker compose up --no-deps --build --force-recreate --remove-orphans
          EOF
